Online_Shop/Online_Shop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.EntityFrameworkCore;
using Online_Shop.Data;
using Online_Shop.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
  [Area("Admin")]
  public class ProductController : Controller
  {
    private ApplicationDbContext _db;
    private IHostingEnvironment _he;

    public ProductController(ApplicationDbContext db,IHostingEnvironment he)
    {
      _db = db;
      _he = he;
  
    }
    public IActionResult Index()
    {
      return View(_db.Products.Include(c=>c.ProductTypes).Include(f=>f.SpecialTags).ToList());
    }

    //POST Index action method
    [HttpPost]
    public IActionResult Index(decimal? lowAmount,decimal? largeAmount)
    {
      var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
      if(lowAmount==null || largeAmount == null)
      {
         products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).ToList();

      }
      return View(products);
    }
    //Get Create method
    public IActionResult Create()
    {
      ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
      ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
      return View();
    }
    //Post Create method
    [HttpPost]
    public async Task<IActionResult>Create(Products products)
    {
      if (ModelState.IsValid)
      {
        var searchProduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
        if (searchProduct != null)
        {
          ViewBag.message = "This Product is already exist";
          ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
          ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
          return View(products);
        }

        if (products.ImgFile != null)
        {

          string ext = Path.GetExtension(products.ImgFile.FileName).ToLower();
          if (ext == ".jpg" || ext == ".png" || ext == ".jpeg")
          {
            string fileName = Path.Combine(_he.WebRootPath, "Images", products.ImgFile.FileName);
            using(var filestream=new FileStream(fileName, FileMode.Create))
            {
            await  products.ImgFile.CopyToAsync(filestream);
              products.Image = "\\Images\\" + products.ImgFile.FileName;
            }
          }
        }
        if (products.ImgFile == null)
        {
          products.Image = "\\Images\\NoImage.png";
        }
        _db.Add(products);
        await _db.SaveChangesAsync();
        TempData["save"] = "Product Type has been saved";
        return RedirectToAction(nameof(Index));
      }
      return View(products);
    }
    //Get Edit Action Method
    public IActionResult Edit(int?id)
    {
      ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
      ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
      if (id == null)
      {
        return NotFound();
      }
      var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
      if (product == null)
      {
        return NotFound();
      }

      return View(product);
    }
    //Post Edit Action Method
    [HttpPost]
    public async Task<IActionResult> Edit(Products products)
    {
      if (ModelState.IsValid)
      {
        //var searchProduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
        //if (searchProduct != null)
        //{
        //  ViewBag.message = "This Product is already exist";
        //  ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
        //  ViewData["TagId"] = new SelectList(_db.SpecialTags.ToList(), "Id", "SpecialTag");
        //  return View(products);
        //}

        if (products.ImgFile != null)
        {

          string ext = Path.GetExtension(products.ImgFile.FileName).ToLower();
          if (ext == ".jpg" || ext == ".png" || ext == ".jpeg")
          {
            string fileName = Path.Combine(_he.WebRootPath, "Images", products.ImgFile.FileName);
            using (var filestream = new FileStream(fileName, FileMode.Create))
            {
              await products.ImgFile.CopyToAsync(filestream);
              products.Image = "\\Images\\" + products.ImgFile.FileName;
            }
          }
        }
        if (products.ImgFile == null)
        {
          products.Image = "\\Images\\NoImage.png";
        }
        _db.Update(products);
        await _db.SaveChangesAsync();
        TempData["update"] = "Product Type has been Updated";
        return RedirectToAction(nameof(Index));
      }
      return View(products);
    }
    //Get Details Action Method
    public IActionResult Details(int?id)
    {
      if (id == null)
      {
        return NotFound();
      }
      var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTags).FirstOrDefault(c => c.Id == id);
      if (product == null)
      {
        return NotFound();
      }
      return View(product);

    }
    //Get Delete Action Method

    public IActionResult Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }
      var product = _db.Products.Include(c=>c.ProductTypes).Include(c=>c.SpecialTags).Where(c => c.Id == id).FirstOrDefault();
      if (product == null)
      {
        return NotFound();
      }
      return View(product);
    }
    //POST delete Action Method
    [HttpPost]
    [ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirm(int?id)
    {
      if (id == null)
      {
        return NotFound();
      }
      var product = _db.Products.FirstOrDefault(c => c.Id == id);
      if (product == null)
      {
        return NotFound();
      }
      _db.Products.Remove(product);
      await _db.SaveChangesAsync();
      TempData["deletedata"] = "Product has been Deleted";
      return RedirectToAction(nameof(Index));

    }

    
   

  }
}

Online_Shop/Online_Shop/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Online_Shop.Data;
using Online_Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductTypesController : Controller
    {
        private ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
    [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }
    //Create Get action Method
    
    public ActionResult Create()
        {
            return View();
        }
        //Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
        TempData["save"] = "Product Type has been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
   
    //Edit Get action Method
    public ActionResult Edit(int?id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }
        //Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
        TempData["update"] = "Product Type has been Updated";
        return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
        //Details Get action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }
        //Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTypes productTypes)
        { 
               
                return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }
        //Delete Post Action Method
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int?id,ProductTypes productTypes)
        {
            if (id == null)
            {
                return NotFound();

            }
            if (id!= productTypes.Id)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
        TempData["deletedata"] = "Product Type has been Deleted";
        return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
    }
}

Online_Shop/Online_Shop/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Shop.Data;
using Online_Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagsController : Controller
    { 
        private ApplicationDbContext _db;

        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.SpecialTags.ToList());
        }
        //Create Get action Method
        public ActionResult Create()
        {
            return View();
        }
        //Create Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.SpecialTags.Add(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }
        //Edit Get action Method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTags.Find(id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }
        //Edit Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.Update(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }
        //Details Get action Method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTags.Find(id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }
        //Details Post Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(SpecialTags specialTags)
        {

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTags.Find(id);
            if (specialtag == null)
            {
                return NotFound();
            }
            return View(specialtag);
        }
        //Delete Post Action Method

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, SpecialTags specialTags)
        {
            if (id == null)
            {
                return NotFound();

            }
            if (id != specialTags.Id)
            {
                return NotFound();
            }
            var specialtag = _db.SpecialTags.Find(id);
            if (specialtag == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(specialtag);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }
    }
}

Online_Shop/Online_Shop/Views/Shared/_ButtonPartial.cshtml
@model int
@*
  For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
  <div class="btn-group">
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    <a asp-action="Details"  class="btn btn-success" asp-route-id="@Model"><i class="fa fa-list" aria-hidden="true"></i></a>
    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model"><i class="fa fa-trash-o" aria-hidden="true"></i></a>

  </div>
</td>
 @*asp-controller="ProductTypes"*@

Online_Shop/Online_Shop/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using Online_Shop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
      products = new List<Products>();
    }
    count = products.Count();
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - Online_Shop</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" />

  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <style>
    .error{
      color:red;
    }
  </style>

</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online_Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
          <partial name="_LoginPartial" />
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Type</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tag</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                @*<i class="fa-solid fa-cart-shopping" aria-hidden="true"></i>*@
                @*<i class="fa-regular fa-cart-shopping"></i>*@
                @*<i class="fa fa-list" aria-hidden="true"></i>*@
                <i class="fa fa-shopping-cart"></i>
                (@count)
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted">
    <div class="container">
      &copy; 2022 - Online_Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @*<script src="https://use.fontawesome.com/501eb715f1.js"></script>*@
  <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

  <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>


  @RenderSection("Scripts", required: false)
</body>
</html>

Online_Shop/Online_Shop/Views/Shared/_PartialView.cshtml
@model string
@*
  For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
  <div class="btn-group">
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fa fa-list" aria-hidden="true"></i></a>
    <a asp-action="Locout" class="btn btn-danger" asp-route-id="@Model"><i class="fa fa-trash-o" aria-hidden="true"></i></a>

  </div>
</td>

Online_Shop/Online_Shop/Views/Shared/_SpecialTagPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTags" class="btn btn-primary" asp-route-id="@Model"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
        <a asp-action="Details" asp-controller="SpecialTags" class="btn btn-success" asp-route-id="@Model"><i class="fa fa-list" aria-hidden="true"></i></a>
        <a asp-action="Delete" asp-controller="SpecialTags" class="btn btn-danger" asp-route-id="@Model"><i class="fa fa-trash-o" aria-hidden="true"></i></a>

    </div>
</td>